apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: db-external-secret
  namespace: demo
spec:
  refreshInterval: "30s" # Quét cập nhật liên tục mỗi 30 giây (Thỏa mãn yêu cầu < 60s)
  secretStoreRef:
    name: aws-secretsmanager-store
    kind: SecretStore
  target:
    name: db-secret-local # Đây là tên K8s Secret được sinh ra tự động trong cụm
    creationPolicy: Owner
  data:
    - secretKey: local_db_password # Key nằm trong K8s Secret cục bộ
      remoteRef:
        key: prod/db/credentials # Tên Secret chính xác trên AWS
        property: db_password   # Tên ô dữ liệu chứa mật khẩu trên AWS