apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: aws-secretsmanager-store
  namespace: demo
spec:
  provider:
    aws:
      service: SecretsManager
      region: ap-southeast-1 # Thay đổi thành vùng AWS của bạn (ví dụ: ap-southeast-1 cho Singapore)
      auth:
        secretRef:
          accessKeyIDSecretRef:
            name: aws-secret-creds
            key: access-key-id
          secretAccessKeySecretRef:
            name: aws-secret-creds
            key: secret-access-key